-- CreateEnum
CREATE TYPE "ArticleType" AS ENUM ('MARFURI', 'MATERII_PRIME', 'MATERIALE_AUXILIARE', 'AMBALAJE', 'OBIECTE_DE_INVENTAR', 'AMENAJARI_PROVIZORII', 'MATERIALE_SPRE_PRELUCRARE', 'MATERIALE_IN_PASTRARE_SAU_CONSIGNATIE', 'DISCOUNT_FINANCIAL_INTRARI', 'COMBUSTIBILI', 'PIESE_DE_SCHIMB', 'ALTE_MATERIALE_CONSUMABILE', 'DISCOUNT_COMERCIAL_INTRARI', 'AMBALAJE_SGR');

-- CreateEnum
CREATE TYPE "UnitOfMeasure" AS ENUM ('BUCATA', 'KILOGRAM', 'LITRU', 'METRU', 'GRAM', 'CUTIE', 'PACHET', 'PUNGA', 'SET', 'METRU_PATRAT', 'METRU_CUB', 'MILIMETRU', 'CENTIMETRU', 'TONA', 'PERECHE', 'SAC', 'MILILITRU', 'KILOWATT_ORA', 'MINUT', 'ORA', 'ZI_DE_LUCRU', 'LUNI_DE_LUCRU', 'DOZA', 'UNITATE_DE_SERVICE', 'O_MIE_DE_BUCATI', 'TRIMESTRU', 'PROCENT', 'KILOMETRU', 'LADA', 'DRY_TONE', 'CENTIMETRU_PATRAT', 'MEGAWATI_ORA', 'ROLA', 'TAMBUR', 'SAC_PLASTIC', 'PALET_LEMN', 'UNITATE', 'TONA_NETA', 'HECTOMETRU_PATRAT', 'FOAIE');

-- CreateEnum
CREATE TYPE "VatRate" AS ENUM ('NINETEEN', 'NINE', 'FIVE');

-- CreateTable
CREATE TABLE "Article" (
    "id" SERIAL NOT NULL,
    "code" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "vat" "VatRate" NOT NULL,
    "unitOfMeasure" "UnitOfMeasure" NOT NULL,
    "type" "ArticleType" NOT NULL,
    "clientCompanyId" INTEGER NOT NULL,

    CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Article_code_key" ON "Article"("code");

-- CreateIndex
CREATE INDEX "Article_clientCompanyId_idx" ON "Article"("clientCompanyId");

-- AddForeignKey
ALTER TABLE "Article" ADD CONSTRAINT "Article_clientCompanyId_fkey" FOREIGN KEY ("clientCompanyId") REFERENCES "ClientCompany"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
